name             'DeamonService'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures DeamonService'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'mca'
depends 'mfs'
depends 'installment'
depends 'inventory'
depends 'mca-service'
depends 'xacct'
depends 'solr-mca'
depends 'solr-log-index'
depends 'flume-sorl'
depends 'mbv-tomcat'
